[package]
name = "Tarot_API"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
hyper = { version = "1.8.1", features = ["full"] }
tokio = { version = "1.49.0", features = ["full"] }
tower = "0.5.3"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"]}
